| Arguments Keep work_dir: C:\Users\JK\PycharmProjects\2025_AAAI\work_dir/dj30_AAAI_AAAI_adam_mse\2025_AAAI_Exp_None_exp_num_0726/130706
rank:None start_date:['2012-02-02']
Epoch 1, train_loss 1.178234, valid_loss 0
Validation loss decreased (inf --> 1.365029).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 2, train_loss 1.155586, valid_loss 0
Validation loss decreased (1.365029 --> 1.361075).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 3, train_loss 1.169833, valid_loss 0
Validation loss decreased (1.361075 --> 1.357216).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 4, train_loss 1.202806, valid_loss 0
Validation loss decreased (1.357216 --> 1.353470).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 5, train_loss 1.172695, valid_loss 0
Validation loss decreased (1.353470 --> 1.349856).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 6, train_loss 1.152344, valid_loss 0
Validation loss decreased (1.349856 --> 1.346321).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 7, train_loss 1.165747, valid_loss 0
Validation loss decreased (1.346321 --> 1.342914).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 8, train_loss 1.187126, valid_loss 0
Validation loss decreased (1.342914 --> 1.339593).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 9, train_loss 1.118536, valid_loss 0
Validation loss decreased (1.339593 --> 1.336351).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 10, train_loss 1.152818, valid_loss 0
Validation loss decreased (1.336351 --> 1.333215).  Saving model ...
Successfully loaded best checkpoint...
Test Best Episode
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2021.1.3\plugins\python\helpers\pydev\pydevd.py", line 1551, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2021.1.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\JK\PycharmProjects\2025_AAAI\run.py", line 239, in <module>
    run(cfg)
  File "C:\Users\JK\PycharmProjects\2025_AAAI\run.py", line 186, in run
    trainer.test()
  File "C:\Users\JK\PycharmProjects\2025_AAAI\trainers\AAAI_mse.py", line 317, in test
    predictions = np.concatenate(gathered_preds)
  File "<__array_function__ internals>", line 200, in concatenate
TypeError: The first input argument needs to be a sequence